name: notebook
channels:
  - conda-forge
dependencies:
  - python=3.10
  - bokeh=3.2.0
  - boto3
  - cartopy=0.21.1 
  - dask=2023.7.0
  - dask-labextension=6.1.0
  - holoviews=1.16.2
  - hvplot=0.8.4
  - intake=0.7.0
  - intake-esm=2023.7.7
  - intake-xarray=0.7.0
  - ipywidgets=8.0.7
  - jupyter-server-proxy=4.0.0
  - jupyterhub-singleuser=4.0.1
  - jupyterlab<4
  - jupyterlab_execute_time
  - nbgitpuller =1.1.1
  - netcdf4=1.6.4
  - notebook=6.4.12
  - matplotlib=3.4.3
  - pip
  - pandas=2.0.3
  - pydot=1.4.2
  - s3fs=2023.6.0
  - scikit-learn=1.3.0
  - scipy=1.11.1
  - shapely=2.0.1
  - tqdm=4.65.0
  - xarray=2023.7.0
  - zarr=2.15.0

