name: ml-extreme-precip
channels:
  - conda-forge
dependencies:
  - python=3.10
  - black=23.9.1
  - bokeh=3.2.2
  - cartopy=0.22.0
  - dask=2023.9.3
  - dask-labextension=7.0.0
  - geopandas=0.14.0
  - geoviews=1.10.1
  - gdal=3.7.2
  - holoviews=1.17.1
  - hvplot=0.8.4
  - ipywidgets=8.1.1
  - jupyter-server-proxy=4.0.0
  - jupyterhub-singleuser=4.0.2 
  - jupyterlab=4.0.5
  - jupyterlab_execute_time=3.0.1
  - keras=2.12.0
  - matplotlib=3.8.0
  - nbgitpuller=1.1.1
  - netcdf4=1.6.4
  - notebook=7.0.3  
  - pip
  - pandas=2.1.1 
  - plotly=5.17.0
  - proj=9.3.0
  - pyproj=3.6.1   
  - pydot=1.2.4
  - rioxarray=0.15.0  
  - scikit-learn=1.3.1 
  - scipy=1.11.3
  - shapely=2.0.1
  - statsmodels
  - tensorflow=2.12.1
  - tqdm=4.66.1
  - xarray=2023.7.0
  - zarr=2.16.1